### ISSUE TITLE
Questions about the two models

### ISSUE THREAD

**Issue by hypsoma** [Solacex/CCM#15]
Hi
 &nbsp; I am a little confused about these two models, **the ImageNet-pretrained Model** and **the Source-only Model**. Why does **the Source-only Model** appear in this ccm_config.yml file？**CCM** and **Source only**, aren't they two different methods ?
https://github.com/Solacex/CCM/blob/4e80b98007219e64d577fb105a35140cb2d13238/config/ccm_config.yml#L70
 &nbsp; In addition, from the section 4.2 of paper, _"We start from DeepLabV2-Res101with the backbone pretrained on the ImageNet. Then we ﬁrstly ﬁnetune the whole network on the source data and use such a source-trained network to initialize the target (adaptation) model."_, **The ImageNet-pretrained Model** should be the adaption model. I am a little confused. THANKS!
 &nbsp; PS: There is a bug with 'News: GTA-4K list is **avalible!**'.

**Comment by Solacex** [comment]
Hello, 
Thanks for your interest in our work!

The training consists of two stages, the source-only stage and the adaptation stage. The two stages of training are conducted consecutively, i.e., the second stage takes the trained model from the first stage as the initialization. 

Thus, the initial weight of source only stage and adaptation stage are imagenet-pretrained model and the source-only model, accordingly.

**Comment by hypsoma** [comment]
THANKS! I get it now.
