### ISSUE TITLE
about the label of target domain

### ISSUE THREAD

**Issue by 2669531054** [Solacex/CCM#19]
hi, I 'm a beginner.
I noticed that in https://github.com/2669531054/CCM/blob/2fcd9cb3b1d2070dd403613f00ca55ef872b3104/trainer/ccm_trainer.py#L203
, you use the label of the train set of target domain to calculate the accuracy of the pseudo label.
I wonder whether this accuracy influence the training process. And if I do not have the label of  the target domain, can I skip this step?

**Comment by Solacex** [comment]
Hello,

The calculated accuracy is just for knowing some necessary statistics. In real world scenario, we could roughly evaluate the model / pseudo labels via validation set.
