### ISSUE TITLE
Source only model

### ISSUE THREAD

**Issue by xdeng7** [Solacex/CCM#2]
Can I use the provided source only model to start training adaptation? (https://drive.google.com/file/d/1-52RggreImwr_BVcGzm41j0mchxclwwu/view) So that I can skip the first step where a large memory GPU is required to train the model.

**Comment by Solacex** [comment]
Yes, you can modify this line to the path of source-only model, so that you can run the stage-2 directly. https://github.com/Solacex/CCM/blob/d526ec260c28c2370ef39137e1a7bb241dbcda20/config/ccm_config.yml#L70

**Comment by xdeng7** [comment]
Thank you. I will try that.

**Comment by xdeng7** [comment]
> Yes, you can modify this line to the path of source-only model, so that you can run the stage-2 directly.
> 
> https://github.com/Solacex/CCM/blob/d526ec260c28c2370ef39137e1a7bb241dbcda20/config/ccm_config.yml#L70

However, the requirement.txt is not provided in this repo. Can't import a bunch of packages.

**Comment by Solacex** [comment]
Hello, I just uploaded the requirements.txt into the repo.
