### ISSUE TITLE
config, writer = init_config("config/final_config.yml", sys.argv)

### ISSUE THREAD

**Issue by gong-lei** [Solacex/CCM#4]
FileNotFoundError: [Errno 2] No such file or directory: 'config/final_config.yml'

I found there are only ccm_config.yml and so_config.yml, so can you provide the final_config.yml?

Thanks so much!

**Comment by Solacex** [comment]
Hello, 
There is a mistake and I will correct it.

To run the code, you just need to modify 'final_config.yml' to 'ccm_config.yml'
